// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace CurrencyConverter.iOS
{
	public partial class CollectionViewController : UICollectionViewController
	{
		public CollectionViewController(IntPtr handle) : base(handle)
		{
		}
	}
}
